name: Dakshin CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Start Server Check
        run: |
          node server.js &
          sleep 5
          pkill node

      - name: Simulate Deployment
        run: |
          echo "Deploying application..."
          sleep 3
          echo "Deployment Successful!"
